name: Scrape Jasoseol Banners

on:
  workflow_dispatch: {}
  schedule:
    # 매주 월요일 01:00 UTC 실행 = 한국시간(KST, UTC+9) 오전(10:00)
    - cron: "0 1 * * 1"

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install -r requirements.txt      
      
      # 서비스계정 JSON을 실제 파일로 저장
      - name: Write service account JSON
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}  # Secrets에 JSON 원문 그대로 저장
        run: |
          printf '%s' "$GDRIVE_SA_JSON" > gdrive_sa.json
          test -s gdrive_sa.json || (echo "gdrive_sa.json is empty!" && exit 1)

      # (강추) 사전검증: 폴더 조회가 되는지 먼저 확인
      - name: Verify Drive folder access
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python - <<'PY'
          import os
          from google.oauth2 import service_account
          from googleapiclient.discovery import build
          creds = service_account.Credentials.from_service_account_file(
              "gdrive_sa.json", scopes=["https://www.googleapis.com/auth/drive"]
          )
          svc = build("drive","v3",credentials=creds)
          meta = svc.files().get(fileId=os.environ["GDRIVE_FOLDER_ID"],
                           fields="id,name,driveId,mimeType",
                           supportsAllDrives=True).execute()
          print("Folder OK:", meta)
          PY
      
      # 크롤링 + 업로드 실행
      - name: Run crawler & upload
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_SA_JSON_PATH: gdrive_sa.json
        run: |
          python jasoseol_banner.py

      # (옵션) 결과물/디버그 아티팩트 업로드
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: jasoseol_banner_outputs
          path: |
            jasoseol_banner.csv
            last_run.txt
            debug_home.html
            debug_next_data.json
          if-no-files-found: warn
